### ISSUE TITLE
Regarding _ssl.so upgradation

### ISSUE THREAD

**Issue by leelaram41** [pypa/virtualenv#1047]
I am facing one issue in python ssl.py file.
we are using python 2.7.3 version where ssl.py file supports only three version of protocol but
For our new feature we require new protocol PROTOCOL_TLSv1_2 is required. When we copy the new ssl.py
We are getting an error of

Traceback (most recent call last):
from _ssl import _SSLContext
ImportError: cannot import name _SSLContext

This error is coming because of _ssl.so file not finding the _SSLContext. Can you please help

How to get the binary files of _ssl.so for 64 bit platform. Even we upgraded the openssl to 1.02k
But still this error is coming. If you have any idea please help us in it.

**Comment by Ivoz** [comment]
Hi, `ssl.PROTOCOL_TLSv1_2` does not exist in python 2.7.3 anyway. Only in 2.7.9 or later.

The new `_SSLContext` infrastructure was patched in 2.7.9 following [pep 466](https://www.python.org/dev/peps/pep-0466/) in order to give Python 2 a more reasonable default TLS security story. However it's a rather large change so trying to mix code from before and after like you have attempted is likely to crash and burn in a lot of cases.

I would suggest you upgrade your Python 2 version to the latest patch version.
