### ISSUE TITLE
Normalize environment config variables names

### ISSUE THREAD

**Issue by romulof** [pypa/virtualenv#1126]
Here are the two exemples that are bugging my OCD:
`VIRTUALENV_PYTHON`
`VIRTUAL_ENV_DISABLE_PROMPT`

Please, choose just one prefix 😄

**Comment by Ivoz** [comment]
The only problem, and the big problem to consider, is backwards compatibility. Do we break someone's long-time working script by changing this in a release? Otherwise I'd be all for it - but BC tends to relegate these kinds of changes until you're doing something big with the code that could break stuff in parallel.

**Comment by pradyunsg** [comment]
Basically, a standard deprecation cycle should be fine for addressing backwards compatibility concerns here.

The next major version that supporting both flavours (current and normalised) and printing a loud? warning when the pre-normalised name is used, would be a good way to go IMO. (the major version after that can remove that support, completing the switch to the newer normalised names)
