### ISSUE TITLE
git bash and documentation problems

### ISSUE THREAD

**Issue by Vandivier** [pypa/virtualenv#1132]
issue 1:  the "edit on GitHub" link is broken on [User Guide > Usage
](https://virtualenv.pypa.io/en/stable/userguide/)

issue 2:  [User Guide > Usage
](https://virtualenv.pypa.io/en/stable/userguide/) mentions known issues with Windows 7 and PowerShell, but it does not document issues with Windows 10 and Git Bash. Below describes the issue I ran into:

1. Generate new [`yo python-lib`](https://gitlab.com/hyper-expanse/generator-python-lib)
2. Configure python3 on PATH and `virtualenv --python=python3 venv`
3. Notice `/venv` generates, along with some children like `/venv/Include`
4. Notice `/venv/bin` fails to generate
5. Obviously, then, you can't `source ./venv/bin/activate`

This is referenced on [the foreign project's Issue 9](https://gitlab.com/hyper-expanse/generator-python-lib/issues/9), but the root cause seems to be incompatibility between virtualenv and Git Bash, unless I'm mistaken please lmk.

**Comment by Vandivier** [comment]
additional note: I attempted to use Cygwin instead of Git Bash to `virtualenv --python="$python3" venv` and still no `./bin`.

At this point I'm really not sure if it is a `virtualenv` problem or a problem with the package I'm using :( New to python.

**Comment by Vandivier** [comment]
I do see in the documentation:
"On Windows, the equivalent activate script is in the Scripts folder:"

But, if I run `\path\to\env\Scripts\activate`, I see no CLI feedback. Fair enough, that doesn't necessarily indicate an issue. But when I then `echo $PATH`, I see an unchanged PATH, which indicates a failure as the doc says:

"this will change your $PATH so its first entry is the virtualenv’s bin/ directory."

Moreover, if I open `\path\to\env\Scripts\activate` as text, the first two lines state:

    # This file must be used with "source bin/activate" *from bash*
    # you cannot run it directly

**Comment by Ivoz** [comment]
I think it's slightly unfortunate, but yes when run on Windows, virtualenv will create a `scripts` folder for activate scripts, instead of a `bin` folder. This is almost entirely an historic decision which is now kept for backwards compatability.

Running a bash or compatible shell is usually a rarer occurance on Windows. When using Windows PowerShell, one must use `activate.ps1` (caveat, see the first 'Note' box [here](https://virtualenv.pypa.io/en/stable/userguide/#activate-script)), or when using Windows Command Prompt, instead use `activate.bat`.

And indeed as the documentation you cannot run the `activate.sh` script directly, neither on a bash terminal in Windows nor in a bash terminal in Linux or OS X. You must source it, usually by `. activate.sh` (note the `.`).

**Comment by hbetts** [comment]
The documentation issue regarding sourcing the `activate` script is entirely my fault. My project, [`generator-python-lib`](https://www.npmjs.com/package/generator-python-lib) was written from my perspective, where I use a Linux system and Bash. Therefore I did not properly document the difference in executing the `activate` script for Windows users.

That has been corrected in the documentation for version `4.0.38`.

@Ivoz can the `activate` script on Windows only be executed from PowerShell or CMD? It sounds like the `.sh` won't work on Windows, so the behavior of Git Bash, `cmder`, or Cygwin, which is to execute the `.sh` file, won't work on Windows.
