### ISSUE TITLE
Dynamically generate VIRTUAL_ENV environment variable

### ISSUE THREAD

**Issue by hsiaoyi0504** [pypa/virtualenv#1166]
Currently, the `VIRTUAL_ENV` environment variable in `activate` script will be generated when virtual environment is created.
However, if we change the name of the folder. It would  not work.

Isn't it better to generate VIRTUAL_ENV variable dynamically using the path of the activate script ?
Maybe I am wrong, but based on my understanding, the activate script is a bash script and we can get the path of this script using mechanism similar to `DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"`.

**Comment by asottile** [comment]
moving a virtualenv is generally not a supported operation as the shebangs (`#!...`) of installed `console_scripts` contain full absolute paths.  (though you can use something like [`virtualenv-tools3`](https://github.com/Yelp/virtualenv-tools) to relocate a venv ~safely)

that said, I had a usecase for almost exactly what's desired here as I'm managing virtualenvs inside `~/.cache/...` and then symlinking them to `./venv` (sorry, closed source tool) and wanted `which python` to resolve as `./venv/bin/python` instead of `~/.cache/ugly long path/bin/python`

I used this chunk of code to accomplish what I wanted:

```python


        def _fixup_activate_file(filename: str, replacement: str) -> None:
            dest = os.path.join(target, 'bin', filename)
            backup = f'{dest}.old'
            os.rename(dest, backup)

            with open(backup) as f:
                contents = f.read()
            with open(dest, 'w') as f:
                f.write(contents.replace(f'"{target}"', replacement))

        # make relocatable activate files
        _fixup_activate_file(
            'activate',
            # bash / zsh (sh not supported, is this ok?)
            '"$(cd "$(dirname "$(dirname "${BASH_SOURCE:0}")")"; pwd)"',
        )
        _fixup_activate_file(
            'activate.fish',
            "(bash -c 'cd '(dirname (dirname (status --current-filename)))'; pwd')",  # noqa: E501
        )
```

note that this *doesn't* work for `sh`, but I only needed to support `bash` / `zsh` / `fish`

**Comment by gaborbernat** [comment]
We no longer support the relocate-able flag, so this is now out of scope too.
