### ISSUE TITLE
virtualenv_directory/include is read-only on Pypy

### ISSUE THREAD

**Issue by inducer** [pypa/virtualenv#1198]
If I run
```
$ pypy ./virtualenv-16.0.0/virtualenv.py zzz
```
then `zzz/include` is a symlink to `/usr/lib/pypy/include` and hence read-only. This makes
```
$ pip install pybind11
```
fail, which (seemingly, legitimately, by way of the `setup(headers=....)` mechanism) wants to write to that location. I should note that on CPython, the `include` directory is not a symlink, allowing modification.

Prior bug: https://github.com/pybind/pybind11/issues/1491

**Comment by gaborbernat** [comment]
@inducer can you try to replicate with latest (``16.2.0``) and if still is true provide a PR patch?

Thanks!

**Comment by inducer** [comment]
Yes, the problem persists with 16.2.0 and Pypy 6.0.

**Comment by daa** [comment]
As I understand this is expected because Python include directory is symlinked but the difference is that for CPython it is ``/usr/include/pythonX.Yz`` but for PyPy it is ``<pypy-dir>/include``. And this difference makes ``<venv-dir>/include`` symlink in case of PyPy. I think it's possible to work around that by disabling symlinking in such case or by always copyiing includes.

**Comment by inducer** [comment]
Yes, I agree--and based on this, I would suggest that `--always-copy` should probably be the default.

**Comment by inducer** [comment]
Thanks!
