### ISSUE TITLE
Move to `src` layout breaks documented "use locally from source" installation method

### ISSUE THREAD

**Issue by evansd** [pypa/virtualenv#1241]
Moving `virtualenv.py` from the project root into a `src` subdirectory breaks the [documented](https://github.com/pypa/virtualenv/blob/4ad2742eec5266c2e42b0651d1cd4b78393699c4/docs/installation.rst) method for running virtualenv from an extracted tarball without installing it.

From a brief test, simply creating a symlink from the old location to the new fixes the issue. But I suppose this won't work on Windows. I wonder if you could create a small shim Python script at the old location which just invokes the script at the new location.

From what I can tell, #1240 is also caused by this change.

**Comment by gaborbernat** [comment]
We need to update the documentation here indeed, no code change should happen/needed.

**Comment by jupe** [comment]
I understand now why #1240 happens, but if you change documented behaviour its then breaking change and major version should be updated. Please could you bring backward compatibility for current v16.x series because otherwise this causes a lot of headache for us - we have to update several dependant modules and new releases for them....

**Comment by gaborbernat** [comment]
Well then, this is unexpected. This documented, but otherwise untested interface. Sadly bringing back API compatibility would be harder and worth it, so I'm thinking of just making a major version change. Can you pin your tool to at most 16.0? We no longer plan to release and 16.x releases.

**Comment by jupe** [comment]
> Can you pin your tool to at most 16.0?

yes we can and did it already here: https://github.com/ARMmbed/node-virtualenv/issues/2 but it doesn’t change that unfortunately fact that existing releases are already broken because of this and we cannot fix them without new releases.. Note that we have been using this tool heavily multiple years without any issues until now so any chance to bring back virtualenv.py to root folder which just import required files from src folder? wouldn’t it do the job? Let me know asap so we know which direction we have go..

**Comment by gaborbernat** [comment]
I would avoid if possible to move it back. And if needed only as a patch release for 16.2. And remove it permanently from root in 17+, which would quickly follow it. Going ahead you should presume it's under source. I don't follow why you need to upgrade existing releases. People wanting to use latest virtualenv should upgrade to your latest version that no longer tries to read from root. I'll add a test to ensure we don't unknowingly break documented installation methods.

**Comment by jupe** [comment]
patch release 16.1.1 is enough for us. 17+ release can break this ”officially” of course.. 

note that node-virtualenv is just one example which depends on this documented file directly. There is probably more. If that file disappears it is breaking change which might cost a lot when products/tools unexpectedly start failing during deployment phase. Its even more complicated when breaking change happens in dependency dependence like now in our case. Anyway, patch release would be more than welcome but we can survive without it even it makes some work for us..

**Comment by gaborbernat** [comment]
We've noted and we'll release a fix after Christmas. Going ahead from next version we'll deprecate this though and encourage people to extract the wheel if they want to use it without installing it.

**Comment by gaborbernat** [comment]
This now is fixed on master and will be released with 16.2 (probably on 31st).

**Comment by gaborbernat** [comment]
Released.
