### ISSUE TITLE
Activate venv within python script to import packages

### ISSUE THREAD

**Issue by gopi1616** [pypa/virtualenv#1290]
if submitting an ENHANCEMENT issue:

It is more of a question/suggestion, not an issue.

Is it possible to activate the virtual environment and use the venv python and its package from the python script instead of having a separate bash script to activate one everytime? I couldn't find any definitive working solution in any online resources for python3 venv. Please let me know if there is a solution or will it be addressed in any future release. Thanks a lot.

**Comment by gaborbernat** [comment]
Please do define your use case what you want to achieve, so I can give an accurate answer. Thanks!

**Comment by mbiokyle29** [comment]
I have been working on something related to this. My use case is:

We have a cookiecutter template that we use to generate our python project skeletons. The goal is that projects created by this template are fully functional and ready to be worked on. Mostly, we want the tests and linting to pass. So I am writing tests for our cookie cutter that do the following
- Generate a project in a temp directory using: https://github.com/hackebrot/pytest-cookies
- Create a virtualenv (from within the py.test execution session) within the new project
- Install the projects dependencies into the venv
- Run `make test` in the venv
- Run `make lint` in the venv

I think this is more or less working (it is however quite scary/messy). Here the code (roughly):
```python
@contextmanager
def bake_in_temp_dir(cookies, restore_venv=False, *args, **kwargs):
    """
    Delete the temporal directory that is created when executing the tests
    :param cookies: pytest_cookies.Cookies, cookie to be baked and its temporal files will be removed
    """
    old_env_venv = os.environ.get("VIRTUAL_ENV")
    old_env_path = os.environ.get("PATH")
    old_real_prefix = getattr(sys, "real_prefix", None)
    old_prefix = getattr(sys, "prefix", None)
    old_path = deepcopy(getattr(sys, "path", None))

    result = cookies.bake(*args, **kwargs)
    try:
        yield result
    finally:

        rmtree(str(result.project))

        if restore_venv:

            if old_env_venv is not None:
                os.environ["VIRTUAL_ENV"] = old_env_venv

            if old_env_path is not None:
                os.environ["PATH"] = old_env_path

            if old_real_prefix is not None:
                sys.real_prefix = old_real_prefix

            if old_prefix is not None:
                sys.prefix = old_prefix

            if old_path is not None:
                sys.path = old_path


with bake_in_temp_dir(cookies, restore_venv=True, extra_context=extra_context) as result:

    assert result.project.isdir()
    assert result.exit_code == 0
    assert result.exception is None

    # create and activate the virtual environment
    venv_dir = os.path.join(result.project, ".venv")
    virtualenv.create_environment(venv_dir)

    activate_file = os.path.join(venv_dir, "bin", "activate_this.py")
    with open(activate_file) as f:
        code = compile(f.read(), activate_file, "exec")
        exec(code, dict(__file__=activate_file))

    check_output_inside_dir(
        "pip install -e . -r requirements_dev.txt --upgrade",
        result.project
    )

    check_output_inside_dir(
        "make lint",
        result.project
    )

    check_output_inside_dir(
        "make test",
        result.project
    )
```

Note that `check_output_inside_dir` is just a helper that runs the command via subprocess after chdir'ing to the correct location.

I will say that doing this multiple times within a session does not appear to work in all cases. I was able to get it working in OSX, but it breaks on linux. The issue (as far as I can tell) is here:
https://github.com/pypa/virtualenv/blob/master/virtualenv.py#L1052

On the second round of creating a venv, this import fails in the subprocess call. I confirmed that  `'/usr/local/lib/python3.6'` is present in `sys.path` when calling the python executable defined h ere: https://github.com/pypa/virtualenv/blob/master/virtualenv.py#L1093 in the first iteration

On the second iteration, the python executable's sys.path does not contain `'/usr/local/lib/python3.6'` and thus cannot find `pkgutil`

I am not sure if this is a bug (likely not) due to the very non-standard stuff I am trying to do. Just thought I'd leave this here since it seems like @gopi1616 was looking to do something similar

**Comment by gaborbernat** [comment]
The described use cases sound like what the project tox (https://tox.readthedocs.io/en/latest/) try to solve, so I'd suggest using that instead.
