### ISSUE TITLE
[ENHANCEMENT] Create activate shell script in root folder of environment

### ISSUE THREAD

**Issue by wyattbiker** [pypa/virtualenv#1315]
virtualenv should automatically generate a .sh script (or .bat) in the same folder as ENV. Will save time, typing source ENV/bin/activate. 

E.g.
```
$ mkdir django-proj
$ cd django-proj
$ virtualenv proj1
$ ls proj1.sh  #// (dsplays proj1.sh script in django-proj folder)
$ ./proj1  #// (executes sources proj1/bin/activate but sets environment in the proper shell stack) 
```

**Comment by gaborbernat** [comment]
This would pollute way too much the root folder, so I would say we can't do this.

**Comment by bskinn** [comment]
I define this alias (short for "virtualenv activate") in my `~/.profile` to make activating environments quicker:

```
vact () {
    source env$1/bin/activate
}
```
Then, for a virtualenv just in `env` all I have to run is `$ vact`; otherwise, if it's, say, `env-test` then I just run `$ vact -test`.

In your case, I'd modify to something like:

```
vact () {
    source $1/bin/activate
}
```
Then you could run `$ vact proj1`. I'd definitely at least add in a check to ensure `$1` is nonzero length, I think... though at the moment there's no file on my system at `/bin/activate` to worry about... so, &lt;shrug&gt;.

**Comment by wyattbiker** [comment]
@bskinn excellent solution. Thanks!
