### ISSUE TITLE
Virtualenv 16.4.0 cannot find ssl module on CentOS

### ISSUE THREAD

**Issue by huangsam** [pypa/virtualenv#1320]
Thanks for submitting an issue!

If submitting a BUG please provide:

- [x] Minimal reproducible example or detailed descriptions
- [x] OS and `pip list` output

Failure with virtualenv 16.4.0:

```
pip install virtualenv==16.4.0
virtualenv venv
source venv/bin/activate
python -c 'import ssl;print("success")' >>> libssl.so cannot be found
```

Success with virtualenv 16.3.0:

```
pip install virtualenv==16.3.0
virtualenv venv
source venv/bin/activate
python -c 'import ssl;print("success")' >>> success
```

Operating System: `CentOS Linux release 7.6.1810 (Core)`

Python Version: `Python 3.7.1`

**Note:** Interestingly enough, 16.4.0 does not fail on Mac OS X High Sierra.

**Comment by tsangwpx** [comment]
I am not sure this useful since I am using the Python 3.7.2 provided by miniconda.

I tried running `ldd` on the missing .so file inside `venv/lib/python3.7/lib-dynload`. It cannot locate the shared library.

For 16.3.0, lib-dynload is symlinked to the one in Python directory.

`(base) aaron@login-0:~/venv/lib/python3.7$ ls -al`
> drwxr-xr-x  2 aaron aaron 12288 Feb 25 18:26 lib-dynload

For 16.4.0, lib-dynload itself is a directory. The *.so files inside are symlinked to the ones in Python directory.

`(base) aaron@login-0:~/venv/lib/python3.7$ ls -al`
> lrwxrwxrwx  1 aaron aaron 52 Feb 25 18:42 lib-dynload -> /home/aaron/miniconda3/lib/python3.7/lib-dynload

**Comment by PythonZero** [comment]
I have a similar problem with windows 10

https://github.com/pypa/virtualenv/issues/1336

**Comment by gaborbernat** [comment]
I think this is not fixed on the rewrite branch.
