### ISSUE TITLE
mayapy support

### ISSUE THREAD

**Issue by gaborbernat** [pypa/virtualenv#1328]
https://help.autodesk.com/cloudhelp/2016/CHS/Maya-Tech-Docs/PyMel/standalone.html 👍 

```
PYTHONHOME is set.  You *must* activate the virtualenv before using it
New python executable in /Users/bernat/git/virtualenv/.tox/maya/bin/python
ERROR: The executable /Users/bernat/git/virtualenv/.tox/maya/bin/python is not functioning
ERROR: It thinks sys.prefix is u'/Applications/Autodesk/maya2019/Maya.app/Contents/Frameworks/Python.framework/Versions/2.7' (should be u'/Users/bernat/git/virtualenv/.tox/maya')
ERROR: virtualenv is not compatible with this system or executable
Running virtualenv with interpreter /Applications/Autodesk/maya2019/Maya.app/Contents/bin/mayapy
```

**Comment by gaborbernat** [comment]
Closing due to lack of interest.

**Comment by martinlanton** [comment]
Hi @gaborbernat I just stumbled on this ticket again while investigating other workarounds to properly setup some CI.

As I mentioned on the other ticket, I would be more than happy to help if I can provide more information.

The only fix I have for now for my test suites for maya components are basically just running on the maya interpreter through this command (instead of using the virtualenv) : 
`commands = C:\Program Files\Autodesk\Maya2018\bin\mayapy -m pytest {[main]project_location}\tests\test_Maya`

This is quite unfortunate as I didn't find a way to make it work with a proper docker just yet or make it run with other toxenvs.

**Comment by gaborbernat** [comment]
You can add virtualenv support of mayapy via a plugin, see https://virtualenv.pypa.io/en/latest/extend.html#creators
