### ISSUE TITLE
MacOS: virtualenv fails if original 'Python' universal binary executable is read-only

### ISSUE THREAD

**Issue by c0d3h4x0r** [pypa/virtualenv#1403]
My company uses a relocatable form of the official MacOS release of Python from Python.org.  We keep that checked into a Perforce repository for use by our build toolchain.  Perforce (unlike git) pulls files down into the local workspace as read-only, so the original Python instance is comprised entirely of files and symlinks lacking the `w` bit.

When we try to use virtualenv to create a virtual environment from that read-only instance, virtualenv fails when it tries to modify the virtual environment's copy of the `Python.app/Contents/MacOS/Python` universal Mach-O executable using `install_name_tool`, because the copy still lacks the `w` bit.

Everywhere that virtualenv calls `install_name_tool` on MacOS, it needs to first ensure the file to be modified is made writable.

**Comment by gaborbernat** [comment]
If you'd like please create a PR with fix against the rewrite branch. The issue seems highly specific to your use case and company, and as such, I don't think anyone will spend time and effort to support it. However, if you propose a solution (maybe behind a flag) I'd be open to considering it accepting it.

**Comment by gaborbernat** [comment]
Closing due to lack of progress.
