### ISSUE TITLE
Consider using release-drafter to update github release notes

### ISSUE THREAD

**Issue by ssbarnea** [pypa/virtualenv#1637]
Currently, the releases notes on releases page on GitHub are empty and, with minimal effort, it would be possible to auto-update them based on merged PRs.

On few projects I used https://github.com/release-drafter/release-drafter to automate it. Basically it uses PR metadata to update the release notes there. 

That is not a proposal to drop the towncrier.

**Comment by gaborbernat** [comment]
This would only make sense if we could make it so that it uses the changelog entries; not commit messages. I don't see an easy way of this now, and would rather not have two separate changelog locations; so, for now, we only populate these under vNext at https://virtualenv.pypa.io/en/latest/changelog.html#release-history; which I think is fine.
