### ISSUE TITLE
Add the `deactivate` script to linux as well

### ISSUE THREAD

**Issue by ShayNehmad** [pypa/virtualenv#1767]
**What's the problem this feature will solve?**

I just tried to execute `venv/bin/deactivate` (on an ubuntu machine, in bash, as part of a build script for my own project called [Infection Monkey](github.com/guardicore/monkey)). It didn't work and I soon realized that I should have just have executed the function `deactivate`, instead. 

**Describe the solution you'd like**

As a QoL improvement, adding the venv/bin/deactivate file sounds good. It can literally be a file that contains the word deactivate and that's it, next to the `activate` file. 

**Alternative Solutions**

The "workaround" is to realize that deactivate is a function and not a file, but that's sometimes too late if you're scripting a build process (like myself). 

**Additional context**

I'm already working on the PR in my fork and will submit it soon 💪

**Comment by gaborbernat** [comment]
I'm tempted to say no to this. There never was a deactivate script. The only contract we committed to is that post-activation typing in deactivate will undo the activation. And this is also what ``venv`` guarantees. In case one tries to call ``venv/bin/deactivate`` the error is quite a descriptive saying that file is missing, so the error is quick and pointing out the mistake. Note this is not just as simple as having a file that has ``decativate`` because we would now need to provide such file for every shell (5+) and ensure all of them work equally as ``deactivate`` function works. Feels a major maintenance burden for a small quality of life improvement. So I'll say thank you very much but we'll not have this for now. If you really want it you can make it a plugin. We'll shelve the implementation in core until there are multiple people requesting it.

**Comment by ShayNehmad** [comment]
Hey @gaborbernat 
I opened a PR, so even though you're inclined to say no, maybe rethink. 
There already is a windows deactivate.bat, so the idea is to make the bash version similar.
You don't have to do it for all the shells as this is a QoL thing, not changing to original contract

**Comment by gaborbernat** [comment]
The sole reason batch script has deactivate is because that shell does not allow defining functions. It's an implementation detail of how we achieve defining the deactivation command, not the contract.


You don't have to do it for all the shells, as this is a QoL thing, not changing the "contract".

On this you're mistaken. If we now say calling decativate via a script is supported that affects all shells we support, as I'd rather not have different contracts per shell.

**Comment by gaborbernat** [comment]
We really need to document the contract of activation scripts to be fair 🤔

**Comment by gaborbernat** [comment]
We actually already do: https://virtualenv.pypa.io/en/latest/user_guide.html#activators

```
The activate script will also modify your shell prompt to indicate which environment is currently active. The script also provisions a deactivate command that will allow you to undo the operation
```

**Comment by ShayNehmad** [comment]
So, in your opinion, if I add the deactivate script to all the shells and add the `source venv/bin/deactivate` option to the documentation, will that be good?

Or would you prefer not having this feature at all?

**Comment by gaborbernat** [comment]
Well, the paths ahead would be that: either we add it to all, or we don't. At the moment I think the deactivated command allows you to achieve the same functionality as the deactivated script does, so to not increase the complexity of the code with little benefit I don't think we had enough request for this to mandate creating 4 more files as part of the virtual environment creation process.
