### ISSUE TITLE
Presence of virtualenv breaks distutils tests

### ISSUE THREAD

**Issue by jaraco** [pypa/virtualenv#1879]
In [pypa/distutils](/pypa/distutils), I'm working on extracting distutils from the stdlib. In pypa/distutils@73ac895667b5bc6e3f5d685e7bad3d4535f07a80, I configured the tests to run on tox, but `test_venv_install_options` was failing. When I ran the tests using `pip-run pytest -- -m pytest`, the tests would pass. After a couple of hours of investigation, I found that the issue was the presence of virtualenv, and in particular, that [virtualenv monkey-patches the Distribution object](https://github.com/pypa/virtualenv/blob/1de7c30f288502caf6f8b91ef9ae1feba697c5e5/src/virtualenv/create/via_global_ref/_virtualenv.py#L32). In
pypa/distutils@c202075affc8a4d03401a4877639a96907438d83, I detect that condition and skip the test.

I also found that using `tox-venv` (venv instead of virtualenv) bypasses the issue, but of course, tox-venv is deprecated.

If this test remains disabled, it will lose its effectiveness. Is there something virtualenv can do to avoid monkey-patching distutils?

**Comment by gaborbernat** [comment]
@jaraco in this case IMHO boils down that some configuration flags of distutils do not make sense in case of a virtual environment; and breaks the invariants guaranteed otherwise by virtual environments. This boils down probably to the fact that distutils was designed and introduced before virtual environments. virtualenv needs to monkey patch the distribution object because without we had multiple people reporting unexpected behaviours when running commands within a virtual environment. IMHO distutils should ignore the options we override via monkeypatching when running within a virtual environment. So I'd argue that that test failing is exposing a bug in distutils, one that has been unadressed for a long time before virtualenv 20, and still not today by venv.

See https://github.com/pypa/virtualenv/issues/1635#issuecomment-590242821 for more details.
