### ISSUE TITLE
The argument --clear is too greedy as of v20

### ISSUE THREAD

**Issue by inno** [pypa/virtualenv#1890]
**Issue**

I've been using ``virtualenv --clear`` for years to flush the virtual environment from local checkouts. This would let me do things such as quickly verify ``requirements.txt`` were aligned with a given project.

After updating to ``20.0.25``, I attempted the same functionality only to discover that my entire local repository and all related files had been deleted. Extremely confused, I dug through the source and discovered a major rewrite as of `20.0.0` had broken the forward-compatibility of this functionality.

In order to save other folks headache and lost work in the future, this functionality should be reverted. I understand it's nowhere near one-to-one, but at the very least, some effort could be made to maintain a majority of non-virtualenv files.

(Pull request to follow)

**Comment by gaborbernat** [comment]
Hello, this is an intended behavioural change; one which I believe we should stick by.

**Comment by inno** [comment]
@gaborbernat I understand the desire to align with ``venv``, but this is a dramatic behavioral change. Simply updating a package should not cause it's arguments to suddenly delete all of your files when that was not the case in previous versions. As it stands, the only user-facing difference is that the help text has been updated, which is ripe for being ignored.

A few alternative options:
  * Prompt when using ``--clear`` to ensure the user wants to delete the entire file tree
  * Use something akin to ``--delete`` for the new behavior and retain ``--clear`` for forward compatibility

**Comment by pradyunsg** [comment]
@inno v20 was, as you noted, a major rewrite accompanied with a major version bump. As @gaborbernat noted, this behaviour change is intentional, and the major version bump denotes that there might be breaking changes in the release such as this one. AFAIK, virtualenv did not make any forward compatibility promises and, further, the 20.0 release for explicitly communicated and documented as a backwards incompatible release.

If you want virtualenv to behave differently, please elaborate on your use case of *why* you want to place non-virtualenv files into the virtualenv directory and why virtualenv should be supporting that use case.

**Comment by gaborbernat** [comment]
> As it stands, the only user-facing difference is that the help text has been updated, which is ripe for being ignored.

The clean flag (or the help text attached to it) never promised selective cleaning, so the fact it did so could be considered just as much a bug as a feature. 

That being said it's a major version release, and we've made quite a few breaking changes. If you want to change this behaviour I'd recommend first raising it as an issue under https://bugs.python.org/, and if upstream adheres to your proposal we can consider adopting here too.
