### ISSUE TITLE
Unknown command '_old_fish_prompt' active.fish 

### ISSUE THREAD

**Issue by gaborbernat** [pypa/virtualenv#1991]
Per @balopat:

Yeah, this is still an issue - https://github.com/pypa/virtualenv/issues/480#issuecomment-285003214 is the right direction. 
Easy to reproduce: 
1. activate virtualenv 
2. `exec fish` 
3. activate virtualenv again 

Fix: before `exec`, `deactivate`

**Comment by itmecho** [comment]
For what it's worth, I fixed this by adding this to my `~/.tmux.conf`

```
set -g default-shell '/usr/bin/fish'
```

After adding that line and restarting my tmux session, I can't reproduce the error at all

**Comment by thomasbbrunner** [comment]
I think I've identified the reason for the bug: 

1. The environment variables set in `activate.fish` are exported to child processes (script uses `set -gx` to set the variables).
2. However, the function `_old_fish_prompt` is not exported to the child processes. 

So, when we run fish from another fish session (such as in tmux), the variables set in `activate.fish` are present in the child process, but the functions are not.

I've written a fix for this, which is to test if the `_old_fish_prompt` exists before attempting to delete it. I can make a PR with this fix.

However, I've stumbled upon another bug: the child fish process has the venv activated, but the fish prompt does not indicate this. This also happens when using bash.

```
thomas@pc:~/code $ printenv | grep -i virtual
thomas@pc:~/code $ source activate
(.venv) thomas@pc:~/code $ printenv | grep -i virtual
VIRTUAL_ENV=/home/thomas/code/.venv
VIRTUAL_ENV_PROMPT=(.venv) 
(.venv) thomas@pc:~/code $ bash
thomas@pc:~/code $ printenv | grep -i virtual
VIRTUAL_ENV=/home/thomas/code/.venv
VIRTUAL_ENV_PROMPT=(.venv) 
```

**Comment by thomasbbrunner** [comment]
This bug has been fixed in the latest virtualenv version. I cannot reproduce it.

I believe people are getting `virtualenv` and `venv` confused here (I know I was). This bug is present in the latest `venv` version. I created an [issue](https://github.com/python/cpython/issues/93858) there.

**Comment by gaborbernat** [comment]
As above.

**Comment by banteg** [comment]
still seeing this in 2024 on `deactivate`

```
fish: Unknown command: _old_fish_prompt
fish:
_old_fish_prompt
^~~~~~~~~~~~~~~^
in command substitution
in function '_warp_prompt'
	called on line 1 of file /var/folders/zq/vyffd7255m38x2mbmvvd102w0000gn/T/.tmpP4yVid
in command substitution
	called on line 120 of file /var/folders/zq/vyffd7255m38x2mbmvvd102w0000gn/T/.tmpP4yVid
in function 'warp_precmd'
in event handler: handler for generic event 'fish_prompt'
fish: Unknown command
        set -l prompt (_old_fish_prompt)
                      ^~~~~~~~~~~~~~~~~^
in function '_warp_prompt'
	called on line 1 of file /var/folders/zq/vyffd7255m38x2mbmvvd102w0000gn/T/.tmpP4yVid
in command substitution
	called on line 120 of file /var/folders/zq/vyffd7255m38x2mbmvvd102w0000gn/T/.tmpP4yVid
in function 'warp_precmd'
in event handler: handler for generic event 'fish_prompt'
```
