### ISSUE TITLE
venv reasonable defaults: Single activator script, default name for venv, auto install from requirements.txt and auto upgrade-deps

### ISSUE THREAD

**Issue by AstroMatt** [pypa/virtualenv#2007]
**What's the problem this feature will solve?**
`Venv` and `virtualenv` are both great tools. As an educator I prefer `venv`, because it's always with Python installation. Therefore this feedback is related to `venv`.

I am using `venv` everyday for last couple of years. I've been programming in Python since 2009 and recently I turned into teaching software engineering. This turn gave me a new perspective.  Pretty often I teach people who first got into programming. Those classes are usually 15 people or more.

At the beginning of a training course I have to teach the following lines:

if you have windows, do:
```bat
python3.9 -m venv python-3.9.0
python-3.9.0/Scripts/activate.bat
```
but if you have Linux or macOS, than
```sh
python3.9 -m venv python-3.9.0
python-3.9.0\bin\activate
```
but if you have different shell than bash (fish, csh, etc. like macOS does).
and then...

Recently this is sent over email, before training course, which is even worse because people are with problems without trainer!

C'mon. Those people are afraid of terminal. Not mentioning:
- changing directory (each system has different paths, separators, permissions),
- there is a `-m venv` parameter which should have space before, inside and after,
- they have to put some duplicate text (like `python3.9` and `python-3.9.0`) in a one line (why?!),
- you have to explain how to check with Python version they have... (`python -v` and `python --version` produces completely different output

Sometimes I waste 30 minutes of training course to help people to setup and activate `venv`!! This ruins the first impression and makes programming inaccessible. I wouldn't dare, to recummend using `venv` for a 3h hands-on workshop on a conference (because it will take so much time for explanation). Why, oh why you need to have different paths, activators and no reasonable defaults? In the other hand, if they start without `venv`, and then install for example `jupyter` with it's all dependencies... it's very messy, and it's too for fixing it...

This makes using `venv` hard for Python newcomers, and this is the reason why they prefer Anaconda.
I don't think this is how we (Python community) should welcome newcomers, by advising to install bloated, 3rd party controlled (with customised settings [such as recursion limit, and whoever knows what else]).

**Describe the solution you'd like**
Creating and setting up `venv` should be no-brainer one command, such as:

`python -m venv --home --activate --install https://example.com/mycourse/requirements.txt`

Let me explain (note, that all of this is backward compatible):

1. `python3.9 -m venv`. If you haven't specified `venv` directory it should by default create a new one with the name `python-3.9.0` (or your current Python version). Simple and backward compatible.

2. A parameter like ``python3.9 -m venv --home`` should place `venv` inside `~/.virtualenvs` directory (of course with default Python version name from example above).

3. Currently, there is no `venv` default name. People are using a lot of different approaches: https://python.astrotech.io/stdlib/modules/venv.html#id2  Having standard name convention (and location) would help much with `.gitignore` file, and prevent from committing those files into repository (it happens more often they you imagine).

4. ``--upgrade-deps`` should be default without need to specify. Each time I've got questions like: why there is information about outdated `pip` after newly created `venv`. If it knows it's outdated, why it was not updated automatically. Which indeed is a very good question. And I also don't understand why. (but this behaviour wouldn't be backward compatible with current behaviour).

5. The most important: activation. Current activators live in different paths ``bin`` or ``Scripts`` which is reflection of Python install directory and I understand why you did that on a developer level. But this should be hidden from end-user during activations! Why activation is not like: `python-3.9.0/activate.py` (where `python-3.9.0` is `venv` name). This script should recognise OS and Shell and use proper script.

6. Activate on creation: `python3.9 -m venv --activate`. This would be handy.

7. Install requirements on creation (This would solve so many problems):
- `python3.9 -m venv --install requirements.txt`
- `python3.9 -m venv --install https://example.com/mycourse/requirements.txt`

8. Of course it should be movable. From your OS you should drag-and-drop to some other location without having to recreate it and without breaking it. People does that, and they wonder why everything breaks.

9. Putting it all together:
- `python -m venv --home --activate --install https://example.com/mycourse/requirements.txt`
- note, that python executable should be without version [a bit controversial for veterans, but for newcomers is a must]. And also it's future proof.

I've seen countless python packages documentation with "Installation guides": if you have windows do this... else do this... This makes `venv` cumbersome for devs who want to share its software with quick installation guide. This makes using `venv` hard for Python newcomers, and this is the reason why they prefer Anaconda. And I don't believe it is a good way to go.

Imagine if you organise a training course or online course and you have to specify installation requirements.
Saying:
1. Install newest Python from https://www.python.org/downloads/
2. Open terminal (this sucks, but it's a necessity).
3. Run `python -m venv --home --activate --install https://example.com/mycourse/requirements.txt`
4. That's it. You're all set-up and ready to participate.

PS.
The last one is not directly related to `venv`. IMHO `venv` should allow other devs, such as  `Jupyter` (or `Jupyter-lab`) to create a shortcut on a desktop after installation. This shortcut should activate `venv` and run `jupyter`. That would be a lifesaver!

**Comment by gaborbernat** [comment]
First, let me say that venv and virtualenv are two totally different projects with totally different maintainers. If you want changes in venv you'll need to open a bug under bugs.python.org, and convince the maintainers there. That being said virtualenv tries to be compatible/plug an play replaceable with venv, so in some areas we do ensure that our interface is compatible with venv.

> 1. `python3.9 -m venv`. If you haven't specified `venv` directory it should by default create a new one with the name `python-3.9.0` (or your current Python version). Simple and backward compatible.

We did have this and people find it confusing so was backed out inside https://github.com/pypa/virtualenv/issues/1556.

> 2\. A parameter like `python3.9 -m venv --home` should place `venv` inside `~/.virtualenvs` directory (of course with default Python version name from example above).

I'm fairly certain that passing the folder name as ``~/.virtualenvs/venv`` solves this.


> 3\. Currently, there is no `venv` default name. People are using a lot of different approaches: [python.astrotech.io/stdlib/modules/venv.html#id2](https://python.astrotech.io/stdlib/modules/venv.html#id2)  Having standard name convention (and location) would help much with `.gitignore` file, and prevent from committing those files into repository (it happens more often they you imagine).

Well, when we did have a default, I picked the name of venv, though many people said they prefer env instead. So I don't think there's a clear winner of what the name should be. However, per 1 there doesn't seem to be an agreement that we should have a default, so what that default is, does not really matter.

> * `--upgrade-deps` should be default without need to specify. Each time I've got questions like: why there is information about outdated `pip` after newly created `venv`. If it knows it's outdated, why it was not updated automatically. Which indeed is a very good question. And I also don't understand why. (but this behaviour wouldn't be backward compatible with current behaviour).

Then teach them to run ``python3.9 -m venv --upgrade-deps venv-name``. The core reason is that venv is not used just by people. It's used by machines in various systems. Pulling in any random new published version is the number one cause of system instability in those cases. Machines like predictable, over brand new. Also pulling in the latest always has a significant performance hit. There's a long topic here https://discuss.python.org/t/how-should-virtualenv-behave-respective-of-seed-packages-e-g-pip-by-default/4146 on the subject.

> 5\. But this should be hidden from end-user during activations! Why activation is not like: `python-3.9.0/activate.py` (where `python-3.9.0` is `venv` name). This script should recognise OS and Shell and use proper script.

Well, this is an interesting proposition. And probably doable. If you're volunteering on writing an activator that's shell and OS agnostic, then we'd accept it. However, I'm not sure technologically it's possible. You can't make it ``python-3.9.0/activate.py`` because that would mean start a new python process, that's a child of the current shell, and child processes can't modify parent processes environments (to which activator scripts essentially boil down). Also, I'm not 100% you can detect always the shell you're running under with. Note, however, you can write a virtualenv plugin to try to do this.

> * Activate on creation: `python3.9 -m venv --activate`. This would be handy.

This goes on the same topic as above. `python3.9 -m venv --activate` is ran in a child process that can't modify the parent process. You could in theory work around it by creating a new shell... but now you're having a shell within a shell that might cause issues in general, though maybe for teaching classes useful enough.

> 7\. Install requirements on creation (This would solve so many problems):

You can add this functionality with a virtualenv plugin, see https://github.com/pypa/virtualenv/issues/1980 for details. If it becomes popular/stable enough we can merge it into the core.

> 1. Of course it should be movable. From your OS you should drag-and-drop to some other location without having to recreate it and without breaking it. People does that, and they wonder why everything breaks.

We tried. But by the design of virtual environments (them being a reference to the host OS python), this is not possible in an OS-agnostic way. See https://github.com/pypa/virtualenv/issues/1549 for more details. That being said if you have a solution that can work, we'd happy to make this possible.

> * note, that python executable should be without version [a bit controversial for veterans, but for newcomers is a must]. And also it's future proof.

Well, again, this is one of those in an ideal world yes. But the operating system doesn't work like that. `python` can point to any number of python interpreters (e.g. will likely be ``python2.7 -> /usr/bin/python`` on MacOs), and we can't install/use any version of python, because some of them will not have the required code.

**Comment by gaborbernat** [comment]
This issue feels like an umbrella one containing too many feature requests. I feel like I addressed all your points. For the ones you want to pursue/continue please open dedicated issues (one issue per feature).
