### ISSUE TITLE
Shell activation hook

### ISSUE THREAD

**Issue by gachdavit** [pypa/virtualenv#2078]
Hello.

I do not know, if this feature is supported (I am in researching process).

Once, my `virtual environment` is activated I want to setup my own `PYTHONPATH` as an `environment variable`. The only solution, I found is to modify `bin/activate` file (But, I do not like this idea). Can I `trigger` some action when `venv` is activated ?

Thanks !

**Comment by earonesty** [comment]
this is similar to my request. https://github.com/pypa/virtualenv/issues/2084  
virtualenv, in general, needs mor hooks.

**Comment by gaborbernat** [comment]
This one here is a harder topic because such activation hooks are shell-dependent. So if we add this feature, we need to implement it 5 times, once for every shell we support. Someone who wants this bad enough would need to investigate how we can achieve this across all shells. I'm not against adding this functionality, but I am against adding it to just one or two shells.

**Comment by gachdavit** [comment]
Thanks !
