### ISSUE TITLE
Can we roll back the use of "Scripts" instead of "bin" in Windows?

### ISSUE THREAD

**Issue by memjr** [pypa/virtualenv#2197]
**What's the problem this feature will solve?**
It's incredibly inconvenient, not to mention ridiculous, that virtual environment stuff gets placed in a Script folder in Windows instead of the usual bin folder.

**Describe the solution you'd like**
Can we roll this back? https://github.com/pypa/virtualenv/commit/993ba1316a83b760370f5a3872b3f5ef4dd904c1

Having to litter projects with multiple Makefiles, batch files, powershell files, or script files in the project's folder so it can accommodate the different paths depending on what OS you're working on.

**Alternative Solutions**

What the possibility to just create link that points bin to Scripts, or Scripts to bin?

**Additional context**

**Comment by gaborbernat** [comment]
> not to mention ridiculous

Please dial back your aggressiveness by two.

> virtual environment stuff gets placed in a Script folded

This is the expected behaviour (for the last fourteen years) and actually required as the ``sysconfig.get_path("scripts")`` mandates this. Would be extremely confusing to change this. This has been raised upstream and rejected, see https://bugs.python.org/issue35003.
