### ISSUE TITLE
Powershell activate script does not reflect the --prompt argument to virtualenv

### ISSUE THREAD

**Issue by psr** [pypa/virtualenv#651]
Creating a new virtualenv using the --prompt does not seem to affect the prompt prefix for the environment in Powershell:

    PS > C:\python27\Scripts\virtualenv.exe --version
    1.11.6
    PS C:\> C:\python27\Scripts\virtualenv.exe --prompt=foo env
    New python executable in env\Scripts\python.exe
    Installing setuptools, pip...done.
    PS C:\> . .\env\Scripts\activate.ps1
    (env) PS >

This only appears to affect Powershell, activating the environment in cmd works correctly

    C:\>env\Scripts\activate.bat
    foo C:\>

**Comment by zmbq** [comment]
I suspect this is because the script is signed so people don't need to change the execution policy to unrestricted. Placing the user-provided prompt inside the script will break the signature.

I wonder why sign the script at all. How many developers don't change the execution policy to Unrestricted anyway?

**Comment by psr** [comment]
That's a good point.  I suppose it would be possible for the activate script to read the prompt from some other file, but that would add complexity compared to other implementations.  I'll close this ticket.

**Comment by zmbq** [comment]
The problem was not resolved. I'll report a one with what I believe is the correct subject.
