### ISSUE TITLE
why is atexit not copied into a virtualenv?

### ISSUE THREAD

**Issue by lebedov** [pypa/virtualenv#748]
I recently came across a [scenario](https://github.com/uqfoundation/dill/issues/91) where the fact that `atexit` is not copied into a virtualenv on creation can cause issues. Is there some reason why it isn't copied?

**Comment by matsjoyce** [comment]
I think the relevant list is at https://github.com/pypa/virtualenv/blob/develop/virtualenv.py#L109-113:
```py
REQUIRED_MODULES = ['os', 'posix', 'posixpath', 'nt', 'ntpath', 'genericpath',
                    'fnmatch', 'locale', 'encodings', 'codecs',
                    'stat', 'UserDict', 'readline', 'copy_reg', 'types',
                    're', 'sre', 'sre_parse', 'sre_constants', 'sre_compile',
                    'zlib']
```

**Comment by Ivoz** [comment]
AFAIK modules are only copied if they refuse to work without being so. Otherwise we're just creating more work for the filesystem copying modules around. However if their location not being the same as a virtualenv's python was the issue, this would mean we would have to copy *all* modules. It seems upstream has fixed to check for base/real prefix.
