### ISSUE TITLE
Can't create 2.7 virtualenv from 3.5 Python install

### ISSUE THREAD

**Issue by jpblair** [pypa/virtualenv#817]
After seeing some of the other issue reports on Windows installs, I did a fresh install of both 2.7 and 3.5, made sure both were 64-bit for consistency, and installed for all users.  I'm successfully able to create a 3.5 virtualenv, but am unable to create a 2.7 virtualenv with the following command:

`virtualenv -p c:/python27/python.exe py2ve`

I get the dreaded error:

`  File "c:\Users\blairj1-v\drydock\lib\os.py", line 379`
`    yield from walk(new_path, topdown, onerror, followlinks)`
`             ^`
`SyntaxError: invalid syntax`
`ERROR: The executable drydock\Scripts\python.exe is not functioning`
`ERROR: It thinks sys.prefix is u'c:\\users\\blairj1-v' (should be u'c:\\users\\blairj1-v\\drydock')`
`ERROR: virtualenv is not compatible with this system or executable`
`Note: some Windows users have reported this error when they installed Python for "Only this user" or have multiple versions of Python installed. Copying the appropriate PythonXX.dll to the virtualenv
Scripts/ directory may fix this problem.`

I have python27.dll in my `py2ve/Scripts` folder, but still nothing.  I know this is a common problem that is supposedly fixed, so apologies if this is just user error.  Thanks for your help.

**Comment by jpblair** [comment]
Looks like I hadn't actually deleted the virtualenv before attempting to recreate it after doing all the reinstalls.  Once I deleted it and then recreated the virtualenv, it appears to work as expected.  Unfortunately Github won't let me delete this issue.

**Comment by oladitan** [comment]
> usr@DESKTOP-#######MINGW64 ~/worldview (master)
$ grunt
Running "exec:python_packages" (exec) task
>> Traceback (most recent call last):
>>   File "C:\Users\usr\worldview\python\lib\site.py", line 67, in <module>
>>     import os
>>   File "C:\Users\usr\worldview\python\lib\os.py", line 409
>>     yield from walk(new_path, topdown, onerror, followlinks)
>>              ^
>> SyntaxError: invalid syntax
Overwriting python\lib\orig-prefix.txt with new content
New python executable in python\Scripts\python.exe
ERROR: The executable python\Scripts\python.exe is not functioning
ERROR: It thinks sys.prefix is u'c:\\users\\usr\\worldview' (should be u'c:\\                                                                                                                                  users\\usr\\worldview\\python')
ERROR: virtualenv is not compatible with this system or executable
Note: some Windows users have reported this error when they installed Python for                                                                                                                                   "Only this user" or have multiple versions of Python installed. Copying the app                                                                                                                                  ropriate PythonXX.dll to the virtualenv Scripts/ directory may fix this problem.
>> Exited with code: 100.
Warning: Task "exec:python_packages" failed. Use --force to continue.

Aborted due to warnings.
