### ISSUE TITLE
--always-copy doesn't always copy

### ISSUE THREAD

**Issue by kevbo** [pypa/virtualenv#818]
When I use --always-copy with virtualenv, I would expect that the environment it creates is completely self-contained with no dependencies outside of its own directory tree. However, that is not the case, as demonstrated in this gist: https://gist.github.com/kevbo/135b4cab839fb8adf357

There are system (well, pyenv) python directories in the path, and even though some modules have been copied, others (like traceback.py) have not.

Is --always-copy intended to create fully-isolated envs, such that I could delete the system python and still allow the env to work?

**Comment by dstufft** [comment]
No. ``--always-copy`` is intended to copy instead of symlink the minimum set of files we need to bootstrap the environment. The "virtual" in virtual environment is supposed to mean that it's not a full or "real" environment. It's largely a flag to disable the "should we symlink or copy" logic incase that detection fails on your machine.

**Comment by fredrikaverpil** [comment]
What if you wish to get a fully-isolated and working python environment within your relocatable virtualenv?
– Is this at all possible?

**Comment by dstufft** [comment]
Sounds like you don't want a virtualenv. You want to go grab Python and just install or build a sack copy.
