### ISSUE TITLE
virtualenv.path_locations has a side-effect of mkdir on windows

### ISSUE THREAD

**Issue by asottile** [pypa/virtualenv#824]
https://github.com/pypa/virtualenv/blob/e657022e5a138a8827d212e8e2f6910416a63986/virtualenv.py#L891

Root cause of https://github.com/pre-commit/pre-commit/issues/299

**Comment by asottile** [comment]
this is still a problem: https://github.com/pypa/virtualenv/blob/59a5ab8ce460de950f97ffba8e1af6d79d530aa9/virtualenv.py#L1076

**Comment by gaborbernat** [comment]
@asottile any idea why that make directory exists?

**Comment by asottile** [comment]
it was introduced in dc6dda8f6c595f40e2cfb5c2db467fabc291d631

my ~guess is that `GetShortPathName` requires that the directory exists

```pycon
>>> import ctypes
>>> get_short_path_name = ctypes.windll.kernel32.GetShortPathNameW
>>> buf = ctypes.create_unicode_buffer(20)
>>> ret = get_short_path_name('hello world', buf, 20)
>>> ret
0
>>> buf
<ctypes.c_wchar_Array_20 object at 0x012CFCB0>
>>> buf.value
''
>>> import os
>>> os.mkdir('hello world')
>>> ret = get_short_path_name('hello world', buf, 20)
>>> buf.value
'HELLOW~1'
```

looks like my guess is correct.  I wonder if the "normalize to remove spaces" is even relevant in 2019

**Comment by gaborbernat** [comment]
With Windows backward compatibility constraints probably it is. Where does this become an issue? Maybe we just document this side-effect, so tools can work around it (by e.g. removing it). I have a sense though that the reason probably is that windows assign short name on the fly by inspecting the content of the directory. So, in theory, is possible that the same long file name, may map to different file paths would they not exist.

**Comment by asottile** [comment]
An example issue is listed in the original issue text, as a hack I'm just using this instead:

https://github.com/pre-commit/pre-commit/blob/570d629a149fad521cca98ce528a1e3d20096ff4/pre_commit/languages/python.py#L21-L24

(that said, in the same release that introduced the `mkdir` it also broke the api in a different way: https://github.com/pre-commit/pre-commit/issues/334)

**Comment by asottile** [comment]
stalebot, I promise you, still an issue: https://github.com/pypa/virtualenv/blob/789cad50b73ecf709c9ed7e6ba7c0e708e7737e2/virtualenv.py#L1116

**Comment by pfmoore** [comment]
The whole `GetShortPathName` business is a bit of a hack - the code comments say "Windows has lots of problems with executables with spaces in the name" but really, that's not true (at least it isn't any more, it may have been in the past). It's quite possible that there's code somewhere that doesn't correctly quote values, but if so, that code should be fixed rather than working around it.

So while the mkdir/GetShortPathName dance may be a necessary evil in the short term, I'd prefer to remove it and see what actual problems exist - it's not clear how we'd know where the problems lie without biting the bullet and removing the workaround. (It's unfortunate that the comment didn't point at any specific issue reports).

(After some checking) Ha, I added that code 7 years ago, replacing the previous code that used pywin32 to do the same thing. Digging further back, it looks like one of the reasons for [the original hack](https://github.com/pypa/virtualenv/commit/dc6dda8f6c595f40e2cfb5c2db467fabc291d631) was https://bugs.launchpad.net/virtualenv/+bug/241581 - which is likely no longer an issue because we now use subprocess to run subprocesses, and that *does* handle spaces correctly.

So there appears to be strong evidence that simply removing the GetShortPathName call would be fine.

**Comment by gaborbernat** [comment]
No longer an issue with the rewrite.
