### ISSUE TITLE
Wrong separated paths for django python/static files when using virtualenv

### ISSUE THREAD

**Issue by alvaromlg** [pypa/virtualenv#854]
Using these packages:
virtualenv==14.0.1
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.1

It install the package in this path: $VIRTUAL_ENV_PATH/lib/python2.7/site-packages/django

but the static django admin files go to $VIRTUAL_ENV_PATH/django/contrib/

But if I use another virutalenv version like theses old ones:
virtualenv==1.5.1
virtualenv-clone==0.2.5
virtualenvwrapper==2.6.1

Then it install everything inside  $VIRTUAL_ENV_PATH/lib/python2.7/site-packages/django with the static django admin files.

Am I missing any option when creating the virtualenv with the virtualenv 14?

Thanks!

**Comment by alvaromlg** [comment]
The change appears from virtualenv version 12 to 13

**Comment by Ivoz** [comment]
what django package(s) are you actually installing? Just `django`? I'm guessing this would be to do with virtualenv >=13 starting off with `pip` version 7 and above.

I'd be greatful if you could try with a virtualenv v12, first run `pip install -U pip` and then see if the same problem occurs.

**Comment by alvaromlg** [comment]
Hello Ivoz.

I am installing an old Django version with pip install Django==1.3

Yes, I checked with virtualenv 12 and it's working fine, the problem occurs when I am using virtualenv >= 13

I am using this pip:
pip --version
pip 7.1.0 from /usr/lib/python2.7/site-packages (python 2.7)

**Comment by Ivoz** [comment]
You are not missing any option.

Later versions of virtualenv come with newer versions of pip and setuptools bundled. However with any virtualenv activate, you can always reinstall an older pip or setuptools. `python -m pip install -U pip==<version> setuptools==<version>`.

I believe it is likely a difference in the setuptools/pip version you are using by default in the virtualenv, and not any difference within virtualenv code itself. I think the difference specifically here is that pip versions after version 7 will repackage the django installation into a wheel before installing, and wheels do not allow absolute path [`data_files`](https://github.com/django/django/blob/stable/1.3.x/setup.py#L83) arguments.

https://packaging.python.org/en/latest/distributing/#data-files

You can downgrade a virtualenv's pip to 6.x, by having that virtualenv activate and running `python -m pip install -U pip~=6.0`

Since django 1.3 is so old I don't believe there's much more support we can give.
