### ISSUE TITLE
The new "download the latest version from the internet" makes virtualenv creation very slow

### ISSUE THREAD

**Issue by pfmoore** [pypa/virtualenv#861]
At work, I'm behind a proxy that pip can't use (NTLM). Access to the internet fails, but takes a long time to do so.

As a result, creating a new virtualenv now takes *six minutes* to complete :-( This makes virtualenv essentially unusable, and have to change my automated virtualenv-creation scripts as a result (either to use the built-in venv module, or virtualenv with ```--never-download```).

I can, of course, use ```--never-download```, but remembering to do this is an issue. We did a lot of work when switching to use of wheels for the bundled packages to make creation of virtualenvs fast, particularly on Windows, and this change has lost most of that benefit. I don't have a machine with internet access available at the moment to check, but I know the download process was a source of a lot of slowness when we did the earlier speedup changes.

Can we revert the default to using the bundled packages, maybe with a ```--latest``` option to download the latest versions for people who don't need fast venv creation, need the latest versions and can't (or won't remember to) run ```python -m pip install -U pip setuptools wheel``` after install?

**Comment by dstufft** [comment]
A lot has changed in the world of packaging since the original download code existed.

I just went ahead and tested this on my local OSX box and this is the timing that I have:

| options            |  time |
|---------------------------------------------|--------|
| no downloading                              | 1.869s |
| downloading w/ a completely empty pip cache | 2.675s |
| downloading w/ a completely full pip cache  | 2.044s |

Even after running it multiple times, the worst time when downloading, is 3.7s. I'm not too excited about a worst case performance penalty of 2 seconds and a best case of a quarter of a second.

This of course assumes everything goes correctly. I'm confused how you managed to get a six minute creation time, we have a 15 second timeout on all HTTP requests with 5 retries and we're going to be requesting ``/simple/{setuptools,wheel,pip}/``. Which comes out to a grand total of 3-4 minutes if your internet is setup in such a way that you're hitting timeouts instead of immediate errors.

I think trying to get the latest version from the internet is a pretty important thing. There was a number of months where creating virtual environments on Python 3.5 meant you got a virtual environment that couldn't create wheels at all because the version of wheel we shipped wasn't compatible with Python 3.5. In addition I think it's a pretty crummy user experience for people to create a virtual environment, and then on their very first invocation of pip they get a warning message saying their pip is out of date. I suspect this will help us get more people onto newer versions faster, particular in situations like Debian/CentOS etc where people will have an older virtualenv that they got from their OS and having them get onto the latest pip even though they're using that older virtualenv.

I think it's nicer than having people run ``python -m pip install -U pip setuptools wheel`` afterwards because not only is the some manual step that's kind of crummy, but that makes the whole thing take even slower since you still have the download, but now you have an uninstall step and an additional install step slowing things down (not to mention the time it takes to literally type out the command if they're not using something like virtualenvwrapper to call it automatically after the creation of a new virtual environment, something that I've heard numerous people say they've been doing).

As far as whether the default should be to download or if the default should be to use the bundled (we have both flags right now, ``--no-download`` and ``--download``) I think the default should be to download. I think that's going to get more people what they actually want. I think that the successfully working case, the time difference is basically a wash, particularly when fully cached.

That being said, I do think it's really crummy that it's taking you 6 minutes to create a virtual environment due to the network access that is involved now by default. It is my assumption that, for most people, they have internet access at any given time *and* for most of them if they don't have internet access it's a matter of policy (like what you have) not a "well in this situation I just don't have internet access" (such as on a plane). I wonder if it'd be an acceptable solution to just make virtualenv respect a configuration file where you can just drop a no-download = true in it so that on your machine, which doesn't have internet access, it just never attempts to access the internet by default?

**Comment by pfmoore** [comment]
Agreed that getting the latest version by default is normally good.

I'm a little unconvinced by numbers from OSX/Linux. When we did the original testing Windows was significantly worse (orders of magnitude, Marcus couldn't believe the results!) But as I can't give reliable figures at the moment, that's not very helpful. I'll do some tests at home tonight.

As to the 6-minute creation time, I am just as baffled as you. But it is a reality, and makes virtualenv unusable.

A "never download" configuration is possible now - setting an environment variable VIRTUALENV_NEVER_DOWNLOAD does the trick (thanks for the suggestion, which prompted me to think of this).

And now that I have that, I can confirm that a "never download" virtualenv creation on my PC (a recent laptop with an SSD) takes 7-8 seconds (average over 3 runs). For comparison, venv takes 6-7 seconds. So as I say, Windows virtualenv creation times are noticeably slower than Unix, even on optimal hardware. The old code was in minutes, IIRC (but as you say, that's no longer relevant). I'll do network overhead tonight, FWIW.

**Comment by dstufft** [comment]
Ah, I had no idea that Windows was just across the board slower for us here. I wonder why, we're both using SSDs so it shouldn't be disk, maybe NTFS is just slower than HFS+ (but I have a hard time believing Windows is using a FS that's significantly slower than other OSs). Maybe Python itself is just slower? Is there an antivirus scanning all files that may be at play here? I don't have any running on OSX.

**Comment by dstufft** [comment]
If I remember correctly, setting environment variables is harder on Windows than on \*nix, so it seems like it'd still be reasonable to make a configuration file?

**Comment by pfmoore** [comment]
It doesn't bother me personally (```$env:VIRTUALENV_NEVER_DOWNLOAD=1``` in my powershell ```$profile``` - I never use anything else for command line) but others might care. I'd say wait for the "me too" votes before bothering with a config file.

**Comment by pfmoore** [comment]
With the network check for the latest version, I get 8-10 seconds per virtualenv creation, which is a bit over 1s (or 15%) extra. Not huge, but not negligible either.

Given that there's a way to configure never-download by default, (there's not only the environment variable, but also virtualenv.ini) I think this can probably be closed.

**Comment by Ivoz** [comment]
I also got a casual count of 8 on my windows boot. (ssd).
